[2025-08-14T01:39:12.077+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [queued]>
[2025-08-14T01:39:12.089+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [queued]>
[2025-08-14T01:39:12.090+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-08-14T01:39:12.103+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): fetch_historical_data> on 2025-08-13 00:00:00+00:00
[2025-08-14T01:39:12.109+0000] {standard_task_runner.py:60} INFO - Started process 71586 to run task
[2025-08-14T01:39:12.111+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'stock_market_batch_pipeline', 'fetch_historical_data', 'scheduled__2025-08-13T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/stock_market_batch_dag.py', '--cfg-path', '/tmp/tmpypriihj9']
[2025-08-14T01:39:12.114+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask fetch_historical_data
[2025-08-14T01:39:12.148+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-08-14T01:39:12.195+0000] {task_command.py:423} INFO - Running <TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [running]> on host 6ea13209f7fc
[2025-08-14T01:39:12.289+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Basanth Kumar' AIRFLOW_CTX_DAG_ID='stock_market_batch_pipeline' AIRFLOW_CTX_TASK_ID='fetch_historical_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-13T00:00:00+00:00'
[2025-08-14T01:39:12.293+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-14T01:39:12.294+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/scripts/batch_data_producer.py 2025-08-13']
[2025-08-14T01:39:12.308+0000] {subprocess.py:86} INFO - Output:
[2025-08-14T01:39:16.359+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-08-14T01:39:16.367+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/scripts/batch_data_producer.py", line 8, in <module>
[2025-08-14T01:39:16.368+0000] {subprocess.py:93} INFO -     import yfinance as yf
[2025-08-14T01:39:16.368+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/yfinance/__init__.py", line 26, in <module>
[2025-08-14T01:39:16.369+0000] {subprocess.py:93} INFO -     from .tickers import Tickers
[2025-08-14T01:39:16.369+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/yfinance/tickers.py", line 26, in <module>
[2025-08-14T01:39:16.369+0000] {subprocess.py:93} INFO -     from . import Ticker, multi
[2025-08-14T01:39:16.369+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/yfinance/multi.py", line 30, in <module>
[2025-08-14T01:39:16.370+0000] {subprocess.py:93} INFO -     import multitasking as _multitasking
[2025-08-14T01:39:16.370+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/multitasking/__init__.py", line 36, in <module>
[2025-08-14T01:39:16.370+0000] {subprocess.py:93} INFO -     class PoolConfig(TypedDict):
[2025-08-14T01:39:16.370+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/multitasking/__init__.py", line 44, in PoolConfig
[2025-08-14T01:39:16.370+0000] {subprocess.py:93} INFO -     engine: Union[type[Thread], type[Process]]  # Execution engine
[2025-08-14T01:39:16.370+0000] {subprocess.py:93} INFO - TypeError: 'type' object is not subscriptable
[2025-08-14T01:39:16.567+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-08-14T01:39:16.625+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-14T01:39:16.647+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_market_batch_pipeline, task_id=fetch_historical_data, execution_date=20250813T000000, start_date=20250814T013912, end_date=20250814T013916
[2025-08-14T01:39:16.693+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 3 for task fetch_historical_data (Bash command failed. The command returned a non-zero exit code 1.; 71586)
[2025-08-14T01:39:16.783+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-14T01:39:16.904+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-14T02:19:17.264+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [queued]>
[2025-08-14T02:19:17.297+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [queued]>
[2025-08-14T02:19:17.298+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-08-14T02:19:17.339+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): fetch_historical_data> on 2025-08-13 00:00:00+00:00
[2025-08-14T02:19:17.375+0000] {standard_task_runner.py:60} INFO - Started process 74116 to run task
[2025-08-14T02:19:17.405+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'stock_market_batch_pipeline', 'fetch_historical_data', 'scheduled__2025-08-13T00:00:00+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/stock_market_batch_dag.py', '--cfg-path', '/tmp/tmp5b3l_ctl']
[2025-08-14T02:19:17.419+0000] {standard_task_runner.py:88} INFO - Job 23: Subtask fetch_historical_data
[2025-08-14T02:19:17.486+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-08-14T02:19:17.563+0000] {task_command.py:423} INFO - Running <TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [running]> on host 6ea13209f7fc
[2025-08-14T02:19:17.736+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Basanth Kumar' AIRFLOW_CTX_DAG_ID='stock_market_batch_pipeline' AIRFLOW_CTX_TASK_ID='fetch_historical_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-13T00:00:00+00:00'
[2025-08-14T02:19:17.748+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-14T02:19:17.754+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/scripts/batch_data_producer.py 2025-08-13']
[2025-08-14T02:19:17.805+0000] {subprocess.py:86} INFO - Output:
[2025-08-14T02:19:22.953+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-08-14T02:19:22.967+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/scripts/batch_data_producer.py", line 8, in <module>
[2025-08-14T02:19:22.979+0000] {subprocess.py:93} INFO -     import yfinance as yf
[2025-08-14T02:19:22.980+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/yfinance/__init__.py", line 26, in <module>
[2025-08-14T02:19:22.980+0000] {subprocess.py:93} INFO -     from .tickers import Tickers
[2025-08-14T02:19:22.980+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/yfinance/tickers.py", line 26, in <module>
[2025-08-14T02:19:22.981+0000] {subprocess.py:93} INFO -     from . import Ticker, multi
[2025-08-14T02:19:22.982+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/yfinance/multi.py", line 30, in <module>
[2025-08-14T02:19:22.982+0000] {subprocess.py:93} INFO -     import multitasking as _multitasking
[2025-08-14T02:19:22.983+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/multitasking/__init__.py", line 36, in <module>
[2025-08-14T02:19:22.984+0000] {subprocess.py:93} INFO -     class PoolConfig(TypedDict):
[2025-08-14T02:19:22.985+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/multitasking/__init__.py", line 44, in PoolConfig
[2025-08-14T02:19:22.986+0000] {subprocess.py:93} INFO -     engine: Union[type[Thread], type[Process]]  # Execution engine
[2025-08-14T02:19:22.986+0000] {subprocess.py:93} INFO - TypeError: 'type' object is not subscriptable
[2025-08-14T02:19:23.412+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-08-14T02:19:23.505+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-14T02:19:23.519+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_market_batch_pipeline, task_id=fetch_historical_data, execution_date=20250813T000000, start_date=20250814T021917, end_date=20250814T021923
[2025-08-14T02:19:23.563+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 23 for task fetch_historical_data (Bash command failed. The command returned a non-zero exit code 1.; 74116)
[2025-08-14T02:19:23.605+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-14T02:19:23.759+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-14T03:48:46.187+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [queued]>
[2025-08-14T03:48:46.195+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [queued]>
[2025-08-14T03:48:46.196+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-08-14T03:48:46.209+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): fetch_historical_data> on 2025-08-13 00:00:00+00:00
[2025-08-14T03:48:46.216+0000] {standard_task_runner.py:60} INFO - Started process 258 to run task
[2025-08-14T03:48:46.227+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'stock_market_batch_pipeline', 'fetch_historical_data', 'scheduled__2025-08-13T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/stock_market_batch_dag.py', '--cfg-path', '/tmp/tmpueh0jlql']
[2025-08-14T03:48:46.231+0000] {standard_task_runner.py:88} INFO - Job 2: Subtask fetch_historical_data
[2025-08-14T03:48:46.283+0000] {task_command.py:423} INFO - Running <TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [running]> on host 0181ae2045ff
[2025-08-14T03:48:46.371+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Basanth Kumar' AIRFLOW_CTX_DAG_ID='stock_market_batch_pipeline' AIRFLOW_CTX_TASK_ID='fetch_historical_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-13T00:00:00+00:00'
[2025-08-14T03:48:46.372+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-14T03:48:46.375+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n    unset PYTHONNOUSERSITE\n    python /opt/***/dags/scripts/batch_data_producer.py 2025-08-13\n    ']
[2025-08-14T03:48:46.383+0000] {subprocess.py:86} INFO - Output:
[2025-08-14T03:48:47.798+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-08-14T03:48:47.802+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/scripts/batch_data_producer.py", line 8, in <module>
[2025-08-14T03:48:47.802+0000] {subprocess.py:93} INFO -     import yfinance as yf
[2025-08-14T03:48:47.803+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'yfinance'
[2025-08-14T03:48:47.872+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-08-14T03:48:47.904+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-14T03:48:47.908+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_market_batch_pipeline, task_id=fetch_historical_data, execution_date=20250813T000000, start_date=20250814T034846, end_date=20250814T034847
[2025-08-14T03:48:47.933+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 2 for task fetch_historical_data (Bash command failed. The command returned a non-zero exit code 1.; 258)
[2025-08-14T03:48:47.975+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-14T03:48:48.057+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
