[2025-08-14T02:41:09.542+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [queued]>
[2025-08-14T02:41:09.557+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [queued]>
[2025-08-14T02:41:09.557+0000] {taskinstance.py:2170} INFO - Starting attempt 9 of 10
[2025-08-14T02:41:09.578+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): fetch_historical_data> on 2025-08-13 00:00:00+00:00
[2025-08-14T02:41:09.586+0000] {standard_task_runner.py:60} INFO - Started process 75554 to run task
[2025-08-14T02:41:09.596+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'stock_market_batch_pipeline', 'fetch_historical_data', 'scheduled__2025-08-13T00:00:00+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/stock_market_batch_dag.py', '--cfg-path', '/tmp/tmpfi6at_1k']
[2025-08-14T02:41:09.604+0000] {standard_task_runner.py:88} INFO - Job 46: Subtask fetch_historical_data
[2025-08-14T02:41:09.655+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-08-14T02:41:09.705+0000] {task_command.py:423} INFO - Running <TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [running]> on host 6ea13209f7fc
[2025-08-14T02:41:09.806+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Basanth Kumar' AIRFLOW_CTX_DAG_ID='stock_market_batch_pipeline' AIRFLOW_CTX_TASK_ID='fetch_historical_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='9' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-13T00:00:00+00:00'
[2025-08-14T02:41:09.812+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-14T02:41:09.813+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/scripts/batch_data_producer.py 2025-08-13']
[2025-08-14T02:41:09.832+0000] {subprocess.py:86} INFO - Output:
[2025-08-14T02:41:17.790+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-08-14T02:41:17.860+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/scripts/batch_data_producer.py", line 8, in <module>
[2025-08-14T02:41:17.878+0000] {subprocess.py:93} INFO -     import yfinance as yf
[2025-08-14T02:41:17.901+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/yfinance/__init__.py", line 26, in <module>
[2025-08-14T02:41:17.913+0000] {subprocess.py:93} INFO -     from .tickers import Tickers
[2025-08-14T02:41:17.971+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/yfinance/tickers.py", line 26, in <module>
[2025-08-14T02:41:18.013+0000] {subprocess.py:93} INFO -     from . import Ticker, multi
[2025-08-14T02:41:18.020+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/yfinance/multi.py", line 30, in <module>
[2025-08-14T02:41:18.024+0000] {subprocess.py:93} INFO -     import multitasking as _multitasking
[2025-08-14T02:41:18.025+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/multitasking/__init__.py", line 36, in <module>
[2025-08-14T02:41:18.026+0000] {subprocess.py:93} INFO -     class PoolConfig(TypedDict):
[2025-08-14T02:41:18.031+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/multitasking/__init__.py", line 44, in PoolConfig
[2025-08-14T02:41:18.053+0000] {subprocess.py:93} INFO -     engine: Union[type[Thread], type[Process]]  # Execution engine
[2025-08-14T02:41:18.058+0000] {subprocess.py:93} INFO - TypeError: 'type' object is not subscriptable
[2025-08-14T02:41:20.147+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-08-14T02:41:20.303+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-14T02:41:20.312+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_market_batch_pipeline, task_id=fetch_historical_data, execution_date=20250813T000000, start_date=20250814T024109, end_date=20250814T024120
[2025-08-14T02:41:20.375+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 46 for task fetch_historical_data (Bash command failed. The command returned a non-zero exit code 1.; 75554)
[2025-08-14T02:41:20.447+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-14T02:41:20.545+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-14T20:14:32.833+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [queued]>
[2025-08-14T20:14:32.842+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [queued]>
[2025-08-14T20:14:32.842+0000] {taskinstance.py:2170} INFO - Starting attempt 9 of 10
[2025-08-14T20:14:32.855+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): fetch_historical_data> on 2025-08-13 00:00:00+00:00
[2025-08-14T20:14:32.860+0000] {standard_task_runner.py:60} INFO - Started process 26083 to run task
[2025-08-14T20:14:32.865+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'stock_market_batch_pipeline', 'fetch_historical_data', 'scheduled__2025-08-13T00:00:00+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/stock_market_batch_dag.py', '--cfg-path', '/tmp/tmpedh0d2hq']
[2025-08-14T20:14:32.867+0000] {standard_task_runner.py:88} INFO - Job 31: Subtask fetch_historical_data
[2025-08-14T20:14:32.918+0000] {task_command.py:423} INFO - Running <TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [running]> on host 0181ae2045ff
[2025-08-14T20:14:32.993+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Basanth Kumar' AIRFLOW_CTX_DAG_ID='stock_market_batch_pipeline' AIRFLOW_CTX_TASK_ID='fetch_historical_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='9' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-13T00:00:00+00:00'
[2025-08-14T20:14:32.993+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-14T20:14:32.994+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n    unset PYTHONNOUSERSITE\n    python /opt/***/dags/scripts/batch_data_producer.py 2025-08-13\n    ']
[2025-08-14T20:14:33.010+0000] {subprocess.py:86} INFO - Output:
[2025-08-14T20:14:33.837+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-08-14T20:14:33.880+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/scripts/batch_data_producer.py", line 8, in <module>
[2025-08-14T20:14:33.908+0000] {subprocess.py:93} INFO -     import yfinance as yf
[2025-08-14T20:14:33.915+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'yfinance'
[2025-08-14T20:14:34.149+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-08-14T20:14:34.214+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-14T20:14:34.223+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_market_batch_pipeline, task_id=fetch_historical_data, execution_date=20250813T000000, start_date=20250814T201432, end_date=20250814T201434
[2025-08-14T20:14:34.267+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 31 for task fetch_historical_data (Bash command failed. The command returned a non-zero exit code 1.; 26083)
[2025-08-14T20:14:34.284+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-14T20:14:34.378+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
