[2025-08-14T02:35:41.952+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [queued]>
[2025-08-14T02:35:41.966+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [queued]>
[2025-08-14T02:35:41.967+0000] {taskinstance.py:2170} INFO - Starting attempt 6 of 7
[2025-08-14T02:35:42.001+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): fetch_historical_data> on 2025-08-13 00:00:00+00:00
[2025-08-14T02:35:42.012+0000] {standard_task_runner.py:60} INFO - Started process 75198 to run task
[2025-08-14T02:35:42.021+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'stock_market_batch_pipeline', 'fetch_historical_data', 'scheduled__2025-08-13T00:00:00+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/stock_market_batch_dag.py', '--cfg-path', '/tmp/tmpp0jz8g24']
[2025-08-14T02:35:42.025+0000] {standard_task_runner.py:88} INFO - Job 39: Subtask fetch_historical_data
[2025-08-14T02:35:42.067+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-08-14T02:35:42.129+0000] {task_command.py:423} INFO - Running <TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [running]> on host 6ea13209f7fc
[2025-08-14T02:35:42.216+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Basanth Kumar' AIRFLOW_CTX_DAG_ID='stock_market_batch_pipeline' AIRFLOW_CTX_TASK_ID='fetch_historical_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-13T00:00:00+00:00'
[2025-08-14T02:35:42.228+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-14T02:35:42.230+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/scripts/batch_data_producer.py 2025-08-13']
[2025-08-14T02:35:42.242+0000] {subprocess.py:86} INFO - Output:
[2025-08-14T02:35:44.981+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-08-14T02:35:44.987+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/scripts/batch_data_producer.py", line 8, in <module>
[2025-08-14T02:35:44.990+0000] {subprocess.py:93} INFO -     import yfinance as yf
[2025-08-14T02:35:44.990+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/yfinance/__init__.py", line 26, in <module>
[2025-08-14T02:35:44.991+0000] {subprocess.py:93} INFO -     from .tickers import Tickers
[2025-08-14T02:35:44.991+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/yfinance/tickers.py", line 26, in <module>
[2025-08-14T02:35:44.992+0000] {subprocess.py:93} INFO -     from . import Ticker, multi
[2025-08-14T02:35:44.992+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/yfinance/multi.py", line 30, in <module>
[2025-08-14T02:35:44.993+0000] {subprocess.py:93} INFO -     import multitasking as _multitasking
[2025-08-14T02:35:44.993+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/multitasking/__init__.py", line 36, in <module>
[2025-08-14T02:35:44.994+0000] {subprocess.py:93} INFO -     class PoolConfig(TypedDict):
[2025-08-14T02:35:44.994+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/multitasking/__init__.py", line 44, in PoolConfig
[2025-08-14T02:35:44.995+0000] {subprocess.py:93} INFO -     engine: Union[type[Thread], type[Process]]  # Execution engine
[2025-08-14T02:35:44.996+0000] {subprocess.py:93} INFO - TypeError: 'type' object is not subscriptable
[2025-08-14T02:35:45.387+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-08-14T02:35:45.509+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-14T02:35:45.520+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_market_batch_pipeline, task_id=fetch_historical_data, execution_date=20250813T000000, start_date=20250814T023541, end_date=20250814T023545
[2025-08-14T02:35:45.563+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 39 for task fetch_historical_data (Bash command failed. The command returned a non-zero exit code 1.; 75198)
[2025-08-14T02:35:45.595+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-14T02:35:45.667+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-14T04:14:22.642+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [queued]>
[2025-08-14T04:14:22.689+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [queued]>
[2025-08-14T04:14:22.689+0000] {taskinstance.py:2170} INFO - Starting attempt 6 of 6
[2025-08-14T04:14:22.739+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): fetch_historical_data> on 2025-08-13 00:00:00+00:00
[2025-08-14T04:14:22.759+0000] {standard_task_runner.py:60} INFO - Started process 1045 to run task
[2025-08-14T04:14:22.829+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'stock_market_batch_pipeline', 'fetch_historical_data', 'scheduled__2025-08-13T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/stock_market_batch_dag.py', '--cfg-path', '/tmp/tmpn1t5u823']
[2025-08-14T04:14:22.847+0000] {standard_task_runner.py:88} INFO - Job 17: Subtask fetch_historical_data
[2025-08-14T04:14:23.136+0000] {task_command.py:423} INFO - Running <TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [running]> on host 0181ae2045ff
[2025-08-14T04:14:23.495+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Basanth Kumar' AIRFLOW_CTX_DAG_ID='stock_market_batch_pipeline' AIRFLOW_CTX_TASK_ID='fetch_historical_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-13T00:00:00+00:00'
[2025-08-14T04:14:23.504+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-14T04:14:23.505+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n    unset PYTHONNOUSERSITE\n    python /opt/***/dags/scripts/batch_data_producer.py 2025-08-13\n    ']
[2025-08-14T04:14:23.543+0000] {subprocess.py:86} INFO - Output:
[2025-08-14T04:14:24.619+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-08-14T04:14:24.627+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/scripts/batch_data_producer.py", line 8, in <module>
[2025-08-14T04:14:24.631+0000] {subprocess.py:93} INFO -     import yfinance as yf
[2025-08-14T04:14:24.634+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'yfinance'
[2025-08-14T04:14:24.705+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-08-14T04:14:24.761+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-14T04:14:24.767+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=stock_market_batch_pipeline, task_id=fetch_historical_data, execution_date=20250813T000000, start_date=20250814T041422, end_date=20250814T041424
[2025-08-14T04:14:24.793+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 17 for task fetch_historical_data (Bash command failed. The command returned a non-zero exit code 1.; 1045)
[2025-08-14T04:14:24.837+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-14T04:14:24.905+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
