[2025-08-14T03:03:48.284+0000] {taskinstance.py:1946} INFO - Dependencies not met for <TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [queued]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'debug_environment'}
[2025-08-14T03:03:48.287+0000] {local_task_job_runner.py:160} INFO - Task is not able to be run
[2025-08-14T21:54:51.771+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [queued]>
[2025-08-14T21:54:51.789+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [queued]>
[2025-08-14T21:54:51.792+0000] {taskinstance.py:2170} INFO - Starting attempt 14 of 14
[2025-08-14T21:54:51.813+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): fetch_historical_data> on 2025-08-13 00:00:00+00:00
[2025-08-14T21:54:51.822+0000] {standard_task_runner.py:60} INFO - Started process 32200 to run task
[2025-08-14T21:54:51.834+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'stock_market_batch_pipeline', 'fetch_historical_data', 'scheduled__2025-08-13T00:00:00+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/stock_market_batch_dag.py', '--cfg-path', '/tmp/tmprth1kzh_']
[2025-08-14T21:54:51.838+0000] {standard_task_runner.py:88} INFO - Job 51: Subtask fetch_historical_data
[2025-08-14T21:54:51.969+0000] {task_command.py:423} INFO - Running <TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [running]> on host 0181ae2045ff
[2025-08-14T21:54:52.084+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Basanth Kumar' AIRFLOW_CTX_DAG_ID='stock_market_batch_pipeline' AIRFLOW_CTX_TASK_ID='fetch_historical_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='14' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-13T00:00:00+00:00'
[2025-08-14T21:54:52.086+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-14T21:54:52.088+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n    unset PYTHONNOUSERSITE\n    export PYTHONPATH=/home/***/.local/lib/python3.8/site-packages\n    cd /opt/***/dags/scripts\n    python batch_data_producer.py 2025-08-13\n    ']
[2025-08-14T21:54:52.103+0000] {subprocess.py:86} INFO - Output:
[2025-08-14T21:54:52.964+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-08-14T21:54:52.971+0000] {subprocess.py:93} INFO -   File "batch_data_producer.py", line 8, in <module>
[2025-08-14T21:54:52.977+0000] {subprocess.py:93} INFO -     import yfinance as yf
[2025-08-14T21:54:52.978+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'yfinance'
[2025-08-14T21:54:53.086+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-08-14T21:54:53.144+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-14T21:54:53.158+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=stock_market_batch_pipeline, task_id=fetch_historical_data, execution_date=20250813T000000, start_date=20250814T215451, end_date=20250814T215453
[2025-08-14T21:54:53.195+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 51 for task fetch_historical_data (Bash command failed. The command returned a non-zero exit code 1.; 32200)
[2025-08-14T21:54:53.238+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-14T21:54:53.348+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
