[2025-08-14T01:44:17.550+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [queued]>
[2025-08-14T01:44:17.554+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [queued]>
[2025-08-14T01:44:17.554+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-08-14T01:44:17.564+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): fetch_historical_data> on 2025-08-13 00:00:00+00:00
[2025-08-14T01:44:17.567+0000] {standard_task_runner.py:60} INFO - Started process 71900 to run task
[2025-08-14T01:44:17.572+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'stock_market_batch_pipeline', 'fetch_historical_data', 'scheduled__2025-08-13T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/stock_market_batch_dag.py', '--cfg-path', '/tmp/tmpzujejgbd']
[2025-08-14T01:44:17.575+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask fetch_historical_data
[2025-08-14T01:44:17.593+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-08-14T01:44:17.635+0000] {task_command.py:423} INFO - Running <TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [running]> on host 6ea13209f7fc
[2025-08-14T01:44:17.690+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Basanth Kumar' AIRFLOW_CTX_DAG_ID='stock_market_batch_pipeline' AIRFLOW_CTX_TASK_ID='fetch_historical_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-13T00:00:00+00:00'
[2025-08-14T01:44:17.691+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-14T01:44:17.692+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/scripts/batch_data_producer.py 2025-08-13']
[2025-08-14T01:44:17.697+0000] {subprocess.py:86} INFO - Output:
[2025-08-14T01:44:18.716+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-08-14T01:44:18.721+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/scripts/batch_data_producer.py", line 8, in <module>
[2025-08-14T01:44:18.722+0000] {subprocess.py:93} INFO -     import yfinance as yf
[2025-08-14T01:44:18.722+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/yfinance/__init__.py", line 26, in <module>
[2025-08-14T01:44:18.722+0000] {subprocess.py:93} INFO -     from .tickers import Tickers
[2025-08-14T01:44:18.723+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/yfinance/tickers.py", line 26, in <module>
[2025-08-14T01:44:18.723+0000] {subprocess.py:93} INFO -     from . import Ticker, multi
[2025-08-14T01:44:18.723+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/yfinance/multi.py", line 30, in <module>
[2025-08-14T01:44:18.723+0000] {subprocess.py:93} INFO -     import multitasking as _multitasking
[2025-08-14T01:44:18.723+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/multitasking/__init__.py", line 36, in <module>
[2025-08-14T01:44:18.724+0000] {subprocess.py:93} INFO -     class PoolConfig(TypedDict):
[2025-08-14T01:44:18.724+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/multitasking/__init__.py", line 44, in PoolConfig
[2025-08-14T01:44:18.725+0000] {subprocess.py:93} INFO -     engine: Union[type[Thread], type[Process]]  # Execution engine
[2025-08-14T01:44:18.725+0000] {subprocess.py:93} INFO - TypeError: 'type' object is not subscriptable
[2025-08-14T01:44:18.839+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-08-14T01:44:18.894+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-14T01:44:18.901+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=stock_market_batch_pipeline, task_id=fetch_historical_data, execution_date=20250813T000000, start_date=20250814T014417, end_date=20250814T014418
[2025-08-14T01:44:18.943+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 5 for task fetch_historical_data (Bash command failed. The command returned a non-zero exit code 1.; 71900)
[2025-08-14T01:44:18.962+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-14T01:44:19.020+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-14T02:23:28.193+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [queued]>
[2025-08-14T02:23:28.205+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [queued]>
[2025-08-14T02:23:28.205+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 3
[2025-08-14T02:23:28.221+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): fetch_historical_data> on 2025-08-13 00:00:00+00:00
[2025-08-14T02:23:28.228+0000] {standard_task_runner.py:60} INFO - Started process 74374 to run task
[2025-08-14T02:23:28.234+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'stock_market_batch_pipeline', 'fetch_historical_data', 'scheduled__2025-08-13T00:00:00+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/stock_market_batch_dag.py', '--cfg-path', '/tmp/tmpsxhbo855']
[2025-08-14T02:23:28.237+0000] {standard_task_runner.py:88} INFO - Job 27: Subtask fetch_historical_data
[2025-08-14T02:23:28.260+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-08-14T02:23:28.300+0000] {task_command.py:423} INFO - Running <TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [running]> on host 6ea13209f7fc
[2025-08-14T02:23:28.373+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Basanth Kumar' AIRFLOW_CTX_DAG_ID='stock_market_batch_pipeline' AIRFLOW_CTX_TASK_ID='fetch_historical_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-13T00:00:00+00:00'
[2025-08-14T02:23:28.376+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-14T02:23:28.377+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/scripts/batch_data_producer.py 2025-08-13']
[2025-08-14T02:23:28.390+0000] {subprocess.py:86} INFO - Output:
[2025-08-14T02:23:30.541+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-08-14T02:23:30.552+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/scripts/batch_data_producer.py", line 8, in <module>
[2025-08-14T02:23:30.553+0000] {subprocess.py:93} INFO -     import yfinance as yf
[2025-08-14T02:23:30.554+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/yfinance/__init__.py", line 26, in <module>
[2025-08-14T02:23:30.554+0000] {subprocess.py:93} INFO -     from .tickers import Tickers
[2025-08-14T02:23:30.555+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/yfinance/tickers.py", line 26, in <module>
[2025-08-14T02:23:30.555+0000] {subprocess.py:93} INFO -     from . import Ticker, multi
[2025-08-14T02:23:30.555+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/yfinance/multi.py", line 30, in <module>
[2025-08-14T02:23:30.556+0000] {subprocess.py:93} INFO -     import multitasking as _multitasking
[2025-08-14T02:23:30.556+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/multitasking/__init__.py", line 36, in <module>
[2025-08-14T02:23:30.556+0000] {subprocess.py:93} INFO -     class PoolConfig(TypedDict):
[2025-08-14T02:23:30.557+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/multitasking/__init__.py", line 44, in PoolConfig
[2025-08-14T02:23:30.557+0000] {subprocess.py:93} INFO -     engine: Union[type[Thread], type[Process]]  # Execution engine
[2025-08-14T02:23:30.557+0000] {subprocess.py:93} INFO - TypeError: 'type' object is not subscriptable
[2025-08-14T02:23:30.749+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-08-14T02:23:30.829+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-14T02:23:30.837+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_market_batch_pipeline, task_id=fetch_historical_data, execution_date=20250813T000000, start_date=20250814T022328, end_date=20250814T022330
[2025-08-14T02:23:30.872+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 27 for task fetch_historical_data (Bash command failed. The command returned a non-zero exit code 1.; 74374)
[2025-08-14T02:23:30.899+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-14T02:23:30.980+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-14T03:50:29.426+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [queued]>
[2025-08-14T03:50:29.431+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [queued]>
[2025-08-14T03:50:29.431+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 3
[2025-08-14T03:50:29.439+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): fetch_historical_data> on 2025-08-13 00:00:00+00:00
[2025-08-14T03:50:29.444+0000] {standard_task_runner.py:60} INFO - Started process 387 to run task
[2025-08-14T03:50:29.452+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'stock_market_batch_pipeline', 'fetch_historical_data', 'scheduled__2025-08-13T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/stock_market_batch_dag.py', '--cfg-path', '/tmp/tmpf1by93oy']
[2025-08-14T03:50:29.455+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask fetch_historical_data
[2025-08-14T03:50:29.506+0000] {task_command.py:423} INFO - Running <TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [running]> on host 0181ae2045ff
[2025-08-14T03:50:29.573+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Basanth Kumar' AIRFLOW_CTX_DAG_ID='stock_market_batch_pipeline' AIRFLOW_CTX_TASK_ID='fetch_historical_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-13T00:00:00+00:00'
[2025-08-14T03:50:29.574+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-14T03:50:29.575+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n    unset PYTHONNOUSERSITE\n    python /opt/***/dags/scripts/batch_data_producer.py 2025-08-13\n    ']
[2025-08-14T03:50:29.586+0000] {subprocess.py:86} INFO - Output:
[2025-08-14T03:50:30.132+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-08-14T03:50:30.134+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/scripts/batch_data_producer.py", line 8, in <module>
[2025-08-14T03:50:30.135+0000] {subprocess.py:93} INFO -     import yfinance as yf
[2025-08-14T03:50:30.135+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'yfinance'
[2025-08-14T03:50:30.224+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-08-14T03:50:30.250+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-14T03:50:30.254+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_market_batch_pipeline, task_id=fetch_historical_data, execution_date=20250813T000000, start_date=20250814T035029, end_date=20250814T035030
[2025-08-14T03:50:30.278+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 5 for task fetch_historical_data (Bash command failed. The command returned a non-zero exit code 1.; 387)
[2025-08-14T03:50:30.309+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-14T03:50:30.435+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
