[2025-08-14T02:30:18.474+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [queued]>
[2025-08-14T02:30:18.482+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [queued]>
[2025-08-14T02:30:18.482+0000] {taskinstance.py:2170} INFO - Starting attempt 4 of 4
[2025-08-14T02:30:18.497+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): fetch_historical_data> on 2025-08-13 00:00:00+00:00
[2025-08-14T02:30:18.502+0000] {standard_task_runner.py:60} INFO - Started process 74828 to run task
[2025-08-14T02:30:18.509+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'stock_market_batch_pipeline', 'fetch_historical_data', 'scheduled__2025-08-13T00:00:00+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/stock_market_batch_dag.py', '--cfg-path', '/tmp/tmpk6qfwrel']
[2025-08-14T02:30:18.513+0000] {standard_task_runner.py:88} INFO - Job 34: Subtask fetch_historical_data
[2025-08-14T02:30:18.537+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-08-14T02:30:18.578+0000] {task_command.py:423} INFO - Running <TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [running]> on host 6ea13209f7fc
[2025-08-14T02:30:18.641+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Basanth Kumar' AIRFLOW_CTX_DAG_ID='stock_market_batch_pipeline' AIRFLOW_CTX_TASK_ID='fetch_historical_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-13T00:00:00+00:00'
[2025-08-14T02:30:18.653+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-14T02:30:18.654+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/scripts/batch_data_producer.py 2025-08-13']
[2025-08-14T02:30:18.666+0000] {subprocess.py:86} INFO - Output:
[2025-08-14T02:30:20.411+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-08-14T02:30:20.423+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/scripts/batch_data_producer.py", line 8, in <module>
[2025-08-14T02:30:20.424+0000] {subprocess.py:93} INFO -     import yfinance as yf
[2025-08-14T02:30:20.425+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/yfinance/__init__.py", line 26, in <module>
[2025-08-14T02:30:20.426+0000] {subprocess.py:93} INFO -     from .tickers import Tickers
[2025-08-14T02:30:20.427+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/yfinance/tickers.py", line 26, in <module>
[2025-08-14T02:30:20.427+0000] {subprocess.py:93} INFO -     from . import Ticker, multi
[2025-08-14T02:30:20.427+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/yfinance/multi.py", line 30, in <module>
[2025-08-14T02:30:20.428+0000] {subprocess.py:93} INFO -     import multitasking as _multitasking
[2025-08-14T02:30:20.428+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/multitasking/__init__.py", line 36, in <module>
[2025-08-14T02:30:20.429+0000] {subprocess.py:93} INFO -     class PoolConfig(TypedDict):
[2025-08-14T02:30:20.429+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/multitasking/__init__.py", line 44, in PoolConfig
[2025-08-14T02:30:20.430+0000] {subprocess.py:93} INFO -     engine: Union[type[Thread], type[Process]]  # Execution engine
[2025-08-14T02:30:20.431+0000] {subprocess.py:93} INFO - TypeError: 'type' object is not subscriptable
[2025-08-14T02:30:20.639+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-08-14T02:30:20.840+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-14T02:30:20.899+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=stock_market_batch_pipeline, task_id=fetch_historical_data, execution_date=20250813T000000, start_date=20250814T023018, end_date=20250814T023020
[2025-08-14T02:30:21.140+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 34 for task fetch_historical_data (Bash command failed. The command returned a non-zero exit code 1.; 74828)
[2025-08-14T02:30:21.183+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-14T02:30:21.370+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-14T03:53:54.906+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [queued]>
[2025-08-14T03:53:54.913+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [queued]>
[2025-08-14T03:53:54.913+0000] {taskinstance.py:2170} INFO - Starting attempt 4 of 5
[2025-08-14T03:53:54.925+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): fetch_historical_data> on 2025-08-13 00:00:00+00:00
[2025-08-14T03:53:54.935+0000] {standard_task_runner.py:60} INFO - Started process 660 to run task
[2025-08-14T03:53:54.943+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'stock_market_batch_pipeline', 'fetch_historical_data', 'scheduled__2025-08-13T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/stock_market_batch_dag.py', '--cfg-path', '/tmp/tmpbimc0szs']
[2025-08-14T03:53:54.948+0000] {standard_task_runner.py:88} INFO - Job 11: Subtask fetch_historical_data
[2025-08-14T03:53:55.014+0000] {task_command.py:423} INFO - Running <TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [running]> on host 0181ae2045ff
[2025-08-14T03:53:55.133+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Basanth Kumar' AIRFLOW_CTX_DAG_ID='stock_market_batch_pipeline' AIRFLOW_CTX_TASK_ID='fetch_historical_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-13T00:00:00+00:00'
[2025-08-14T03:53:55.136+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-14T03:53:55.138+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n    unset PYTHONNOUSERSITE\n    python /opt/***/dags/scripts/batch_data_producer.py 2025-08-13\n    ']
[2025-08-14T03:53:55.157+0000] {subprocess.py:86} INFO - Output:
[2025-08-14T03:53:55.868+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-08-14T03:53:55.880+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/scripts/batch_data_producer.py", line 8, in <module>
[2025-08-14T03:53:55.886+0000] {subprocess.py:93} INFO -     import yfinance as yf
[2025-08-14T03:53:55.887+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'yfinance'
[2025-08-14T03:53:55.978+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-08-14T03:53:56.167+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-14T03:53:56.197+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_market_batch_pipeline, task_id=fetch_historical_data, execution_date=20250813T000000, start_date=20250814T035354, end_date=20250814T035356
[2025-08-14T03:53:56.248+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 11 for task fetch_historical_data (Bash command failed. The command returned a non-zero exit code 1.; 660)
[2025-08-14T03:53:56.286+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-14T03:53:56.394+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
