[2025-08-14T02:51:04.736+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [queued]>
[2025-08-14T02:51:04.744+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [queued]>
[2025-08-14T02:51:04.744+0000] {taskinstance.py:2170} INFO - Starting attempt 11 of 12
[2025-08-14T02:51:04.775+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): fetch_historical_data> on 2025-08-13 00:00:00+00:00
[2025-08-14T02:51:04.788+0000] {standard_task_runner.py:60} INFO - Started process 76184 to run task
[2025-08-14T02:51:04.803+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'stock_market_batch_pipeline', 'fetch_historical_data', 'scheduled__2025-08-13T00:00:00+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/stock_market_batch_dag.py', '--cfg-path', '/tmp/tmp1xzjzngw']
[2025-08-14T02:51:04.806+0000] {standard_task_runner.py:88} INFO - Job 57: Subtask fetch_historical_data
[2025-08-14T02:51:04.841+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-08-14T02:51:04.950+0000] {task_command.py:423} INFO - Running <TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [running]> on host 6ea13209f7fc
[2025-08-14T02:51:05.085+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Basanth Kumar' AIRFLOW_CTX_DAG_ID='stock_market_batch_pipeline' AIRFLOW_CTX_TASK_ID='fetch_historical_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='11' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-13T00:00:00+00:00'
[2025-08-14T02:51:05.087+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-14T02:51:05.088+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/scripts/batch_data_producer.py 2025-08-13']
[2025-08-14T02:51:05.117+0000] {subprocess.py:86} INFO - Output:
[2025-08-14T02:51:17.816+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-08-14T02:51:17.840+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/scripts/batch_data_producer.py", line 8, in <module>
[2025-08-14T02:51:17.841+0000] {subprocess.py:93} INFO -     import yfinance as yf
[2025-08-14T02:51:17.842+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/yfinance/__init__.py", line 26, in <module>
[2025-08-14T02:51:17.844+0000] {subprocess.py:93} INFO -     from .tickers import Tickers
[2025-08-14T02:51:17.850+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/yfinance/tickers.py", line 26, in <module>
[2025-08-14T02:51:17.851+0000] {subprocess.py:93} INFO -     from . import Ticker, multi
[2025-08-14T02:51:17.851+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/yfinance/multi.py", line 30, in <module>
[2025-08-14T02:51:17.852+0000] {subprocess.py:93} INFO -     import multitasking as _multitasking
[2025-08-14T02:51:17.852+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/multitasking/__init__.py", line 36, in <module>
[2025-08-14T02:51:17.853+0000] {subprocess.py:93} INFO -     class PoolConfig(TypedDict):
[2025-08-14T02:51:17.853+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/multitasking/__init__.py", line 44, in PoolConfig
[2025-08-14T02:51:17.854+0000] {subprocess.py:93} INFO -     engine: Union[type[Thread], type[Process]]  # Execution engine
[2025-08-14T02:51:17.855+0000] {subprocess.py:93} INFO - TypeError: 'type' object is not subscriptable
[2025-08-14T02:51:19.059+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-08-14T02:51:19.198+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-14T02:51:19.210+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_market_batch_pipeline, task_id=fetch_historical_data, execution_date=20250813T000000, start_date=20250814T025104, end_date=20250814T025119
[2025-08-14T02:51:19.268+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 57 for task fetch_historical_data (Bash command failed. The command returned a non-zero exit code 1.; 76184)
[2025-08-14T02:51:19.342+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-14T02:51:19.495+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-14T21:42:13.314+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [queued]>
[2025-08-14T21:42:13.321+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [queued]>
[2025-08-14T21:42:13.324+0000] {taskinstance.py:2170} INFO - Starting attempt 11 of 12
[2025-08-14T21:42:13.335+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): fetch_historical_data> on 2025-08-13 00:00:00+00:00
[2025-08-14T21:42:13.350+0000] {standard_task_runner.py:60} INFO - Started process 31299 to run task
[2025-08-14T21:42:13.355+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'stock_market_batch_pipeline', 'fetch_historical_data', 'scheduled__2025-08-13T00:00:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/stock_market_batch_dag.py', '--cfg-path', '/tmp/tmp4l27tcz3']
[2025-08-14T21:42:13.359+0000] {standard_task_runner.py:88} INFO - Job 36: Subtask fetch_historical_data
[2025-08-14T21:42:13.412+0000] {task_command.py:423} INFO - Running <TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [running]> on host 0181ae2045ff
[2025-08-14T21:42:13.533+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Basanth Kumar' AIRFLOW_CTX_DAG_ID='stock_market_batch_pipeline' AIRFLOW_CTX_TASK_ID='fetch_historical_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='11' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-13T00:00:00+00:00'
[2025-08-14T21:42:13.538+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-14T21:42:13.555+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n    unset PYTHONNOUSERSITE\n    python /opt/***/dags/scripts/batch_data_producer.py 2025-08-13\n    ']
[2025-08-14T21:42:13.570+0000] {subprocess.py:86} INFO - Output:
[2025-08-14T21:42:14.565+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-08-14T21:42:14.590+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/scripts/batch_data_producer.py", line 8, in <module>
[2025-08-14T21:42:14.592+0000] {subprocess.py:93} INFO -     import yfinance as yf
[2025-08-14T21:42:14.597+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'yfinance'
[2025-08-14T21:42:14.763+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-08-14T21:42:14.815+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-14T21:42:14.829+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_market_batch_pipeline, task_id=fetch_historical_data, execution_date=20250813T000000, start_date=20250814T214213, end_date=20250814T214214
[2025-08-14T21:42:14.855+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 36 for task fetch_historical_data (Bash command failed. The command returned a non-zero exit code 1.; 31299)
[2025-08-14T21:42:14.867+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-14T21:42:14.925+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
