[2025-08-14T03:03:49.040+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [queued]> finished (success) although the task says it's queued. (Info: None) Was the task killed externally?
