[2025-08-14T02:35:48.709+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [queued]>
[2025-08-14T02:35:48.728+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [queued]>
[2025-08-14T02:35:48.729+0000] {taskinstance.py:2170} INFO - Starting attempt 7 of 8
[2025-08-14T02:35:48.788+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): fetch_historical_data> on 2025-08-13 00:00:00+00:00
[2025-08-14T02:35:48.797+0000] {standard_task_runner.py:60} INFO - Started process 75221 to run task
[2025-08-14T02:35:48.811+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'stock_market_batch_pipeline', 'fetch_historical_data', 'scheduled__2025-08-13T00:00:00+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/stock_market_batch_dag.py', '--cfg-path', '/tmp/tmpt9469kdr']
[2025-08-14T02:35:48.814+0000] {standard_task_runner.py:88} INFO - Job 40: Subtask fetch_historical_data
[2025-08-14T02:35:48.843+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-08-14T02:35:48.886+0000] {task_command.py:423} INFO - Running <TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [running]> on host 6ea13209f7fc
[2025-08-14T02:35:49.063+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Basanth Kumar' AIRFLOW_CTX_DAG_ID='stock_market_batch_pipeline' AIRFLOW_CTX_TASK_ID='fetch_historical_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='7' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-13T00:00:00+00:00'
[2025-08-14T02:35:49.080+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-14T02:35:49.085+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/scripts/batch_data_producer.py 2025-08-13']
[2025-08-14T02:35:49.116+0000] {subprocess.py:86} INFO - Output:
[2025-08-14T02:35:51.723+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-08-14T02:35:51.748+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/scripts/batch_data_producer.py", line 8, in <module>
[2025-08-14T02:35:51.750+0000] {subprocess.py:93} INFO -     import yfinance as yf
[2025-08-14T02:35:51.751+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/yfinance/__init__.py", line 26, in <module>
[2025-08-14T02:35:51.751+0000] {subprocess.py:93} INFO -     from .tickers import Tickers
[2025-08-14T02:35:51.752+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/yfinance/tickers.py", line 26, in <module>
[2025-08-14T02:35:51.753+0000] {subprocess.py:93} INFO -     from . import Ticker, multi
[2025-08-14T02:35:51.753+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/yfinance/multi.py", line 30, in <module>
[2025-08-14T02:35:51.754+0000] {subprocess.py:93} INFO -     import multitasking as _multitasking
[2025-08-14T02:35:51.755+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/multitasking/__init__.py", line 36, in <module>
[2025-08-14T02:35:51.756+0000] {subprocess.py:93} INFO -     class PoolConfig(TypedDict):
[2025-08-14T02:35:51.757+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/multitasking/__init__.py", line 44, in PoolConfig
[2025-08-14T02:35:51.758+0000] {subprocess.py:93} INFO -     engine: Union[type[Thread], type[Process]]  # Execution engine
[2025-08-14T02:35:51.759+0000] {subprocess.py:93} INFO - TypeError: 'type' object is not subscriptable
[2025-08-14T02:35:52.317+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-08-14T02:35:52.409+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-14T02:35:52.424+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_market_batch_pipeline, task_id=fetch_historical_data, execution_date=20250813T000000, start_date=20250814T023548, end_date=20250814T023552
[2025-08-14T02:35:52.478+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 40 for task fetch_historical_data (Bash command failed. The command returned a non-zero exit code 1.; 75221)
[2025-08-14T02:35:52.551+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-14T02:35:52.779+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-14T20:08:56.874+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [queued]>
[2025-08-14T20:08:56.881+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [queued]>
[2025-08-14T20:08:56.881+0000] {taskinstance.py:2170} INFO - Starting attempt 7 of 8
[2025-08-14T20:08:56.893+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): fetch_historical_data> on 2025-08-13 00:00:00+00:00
[2025-08-14T20:08:56.900+0000] {standard_task_runner.py:60} INFO - Started process 25666 to run task
[2025-08-14T20:08:56.902+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'stock_market_batch_pipeline', 'fetch_historical_data', 'scheduled__2025-08-13T00:00:00+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/stock_market_batch_dag.py', '--cfg-path', '/tmp/tmptqzyymc5']
[2025-08-14T20:08:56.905+0000] {standard_task_runner.py:88} INFO - Job 23: Subtask fetch_historical_data
[2025-08-14T20:08:56.953+0000] {task_command.py:423} INFO - Running <TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [running]> on host 0181ae2045ff
[2025-08-14T20:08:57.031+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Basanth Kumar' AIRFLOW_CTX_DAG_ID='stock_market_batch_pipeline' AIRFLOW_CTX_TASK_ID='fetch_historical_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='7' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-13T00:00:00+00:00'
[2025-08-14T20:08:57.035+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-14T20:08:57.038+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n    unset PYTHONNOUSERSITE\n    python /opt/***/dags/scripts/batch_data_producer.py 2025-08-13\n    ']
[2025-08-14T20:08:57.049+0000] {subprocess.py:86} INFO - Output:
[2025-08-14T20:08:58.153+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-08-14T20:08:58.159+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/scripts/batch_data_producer.py", line 8, in <module>
[2025-08-14T20:08:58.161+0000] {subprocess.py:93} INFO -     import yfinance as yf
[2025-08-14T20:08:58.161+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'yfinance'
[2025-08-14T20:08:58.235+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-08-14T20:08:58.267+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-14T20:08:58.275+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_market_batch_pipeline, task_id=fetch_historical_data, execution_date=20250813T000000, start_date=20250814T200856, end_date=20250814T200858
[2025-08-14T20:08:58.295+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 23 for task fetch_historical_data (Bash command failed. The command returned a non-zero exit code 1.; 25666)
[2025-08-14T20:08:58.316+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-14T20:08:58.355+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
