[2025-08-14T02:31:08.684+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [queued]>
[2025-08-14T02:31:08.693+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [queued]>
[2025-08-14T02:31:08.693+0000] {taskinstance.py:2170} INFO - Starting attempt 5 of 6
[2025-08-14T02:31:08.702+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): fetch_historical_data> on 2025-08-13 00:00:00+00:00
[2025-08-14T02:31:08.714+0000] {standard_task_runner.py:60} INFO - Started process 74913 to run task
[2025-08-14T02:31:08.722+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'stock_market_batch_pipeline', 'fetch_historical_data', 'scheduled__2025-08-13T00:00:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/stock_market_batch_dag.py', '--cfg-path', '/tmp/tmp_x3vj65u']
[2025-08-14T02:31:08.729+0000] {standard_task_runner.py:88} INFO - Job 36: Subtask fetch_historical_data
[2025-08-14T02:31:08.761+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-08-14T02:31:08.799+0000] {task_command.py:423} INFO - Running <TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [running]> on host 6ea13209f7fc
[2025-08-14T02:31:08.874+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Basanth Kumar' AIRFLOW_CTX_DAG_ID='stock_market_batch_pipeline' AIRFLOW_CTX_TASK_ID='fetch_historical_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-13T00:00:00+00:00'
[2025-08-14T02:31:08.880+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-14T02:31:08.881+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/scripts/batch_data_producer.py 2025-08-13']
[2025-08-14T02:31:08.889+0000] {subprocess.py:86} INFO - Output:
[2025-08-14T02:31:11.663+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-08-14T02:31:11.677+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/scripts/batch_data_producer.py", line 8, in <module>
[2025-08-14T02:31:11.679+0000] {subprocess.py:93} INFO -     import yfinance as yf
[2025-08-14T02:31:11.680+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/yfinance/__init__.py", line 26, in <module>
[2025-08-14T02:31:11.681+0000] {subprocess.py:93} INFO -     from .tickers import Tickers
[2025-08-14T02:31:11.681+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/yfinance/tickers.py", line 26, in <module>
[2025-08-14T02:31:11.682+0000] {subprocess.py:93} INFO -     from . import Ticker, multi
[2025-08-14T02:31:11.682+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/yfinance/multi.py", line 30, in <module>
[2025-08-14T02:31:11.682+0000] {subprocess.py:93} INFO -     import multitasking as _multitasking
[2025-08-14T02:31:11.683+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/multitasking/__init__.py", line 36, in <module>
[2025-08-14T02:31:11.683+0000] {subprocess.py:93} INFO -     class PoolConfig(TypedDict):
[2025-08-14T02:31:11.684+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/multitasking/__init__.py", line 44, in PoolConfig
[2025-08-14T02:31:11.684+0000] {subprocess.py:93} INFO -     engine: Union[type[Thread], type[Process]]  # Execution engine
[2025-08-14T02:31:11.684+0000] {subprocess.py:93} INFO - TypeError: 'type' object is not subscriptable
[2025-08-14T02:31:12.000+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-08-14T02:31:12.086+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-14T02:31:12.092+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_market_batch_pipeline, task_id=fetch_historical_data, execution_date=20250813T000000, start_date=20250814T023108, end_date=20250814T023112
[2025-08-14T02:31:12.133+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 36 for task fetch_historical_data (Bash command failed. The command returned a non-zero exit code 1.; 74913)
[2025-08-14T02:31:12.174+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-14T02:31:12.236+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-14T03:56:26.238+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [queued]>
[2025-08-14T03:56:26.246+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [queued]>
[2025-08-14T03:56:26.247+0000] {taskinstance.py:2170} INFO - Starting attempt 5 of 6
[2025-08-14T03:56:26.259+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): fetch_historical_data> on 2025-08-13 00:00:00+00:00
[2025-08-14T03:56:26.269+0000] {standard_task_runner.py:60} INFO - Started process 858 to run task
[2025-08-14T03:56:26.274+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'stock_market_batch_pipeline', 'fetch_historical_data', 'scheduled__2025-08-13T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/stock_market_batch_dag.py', '--cfg-path', '/tmp/tmpf2dolds7']
[2025-08-14T03:56:26.277+0000] {standard_task_runner.py:88} INFO - Job 15: Subtask fetch_historical_data
[2025-08-14T03:56:26.334+0000] {task_command.py:423} INFO - Running <TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [running]> on host 0181ae2045ff
[2025-08-14T03:56:26.466+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Basanth Kumar' AIRFLOW_CTX_DAG_ID='stock_market_batch_pipeline' AIRFLOW_CTX_TASK_ID='fetch_historical_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-13T00:00:00+00:00'
[2025-08-14T03:56:26.467+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-14T03:56:26.469+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n    unset PYTHONNOUSERSITE\n    python /opt/***/dags/scripts/batch_data_producer.py 2025-08-13\n    ']
[2025-08-14T03:56:26.482+0000] {subprocess.py:86} INFO - Output:
[2025-08-14T03:56:27.358+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-08-14T03:56:27.381+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/scripts/batch_data_producer.py", line 8, in <module>
[2025-08-14T03:56:27.383+0000] {subprocess.py:93} INFO -     import yfinance as yf
[2025-08-14T03:56:27.385+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'yfinance'
[2025-08-14T03:56:27.551+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-08-14T03:56:27.750+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-14T03:56:27.788+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_market_batch_pipeline, task_id=fetch_historical_data, execution_date=20250813T000000, start_date=20250814T035626, end_date=20250814T035627
[2025-08-14T03:56:27.847+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 15 for task fetch_historical_data (Bash command failed. The command returned a non-zero exit code 1.; 858)
[2025-08-14T03:56:27.874+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-14T03:56:28.028+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
