[2025-08-14T02:58:25.488+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [queued]>
[2025-08-14T02:58:25.513+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [queued]>
[2025-08-14T02:58:25.514+0000] {taskinstance.py:2170} INFO - Starting attempt 13 of 14
[2025-08-14T02:58:25.568+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): fetch_historical_data> on 2025-08-13 00:00:00+00:00
[2025-08-14T02:58:25.626+0000] {standard_task_runner.py:60} INFO - Started process 76747 to run task
[2025-08-14T02:58:25.764+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'stock_market_batch_pipeline', 'fetch_historical_data', 'scheduled__2025-08-13T00:00:00+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/stock_market_batch_dag.py', '--cfg-path', '/tmp/tmpwwr4umsp']
[2025-08-14T02:58:25.797+0000] {standard_task_runner.py:88} INFO - Job 67: Subtask fetch_historical_data
[2025-08-14T02:58:25.933+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-08-14T02:58:26.227+0000] {task_command.py:423} INFO - Running <TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [running]> on host 6ea13209f7fc
[2025-08-14T02:58:26.618+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Basanth Kumar' AIRFLOW_CTX_DAG_ID='stock_market_batch_pipeline' AIRFLOW_CTX_TASK_ID='fetch_historical_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='13' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-13T00:00:00+00:00'
[2025-08-14T02:58:26.628+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-14T02:58:26.630+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'PYTHONPATH=/usr/local/lib/python3.8/site-packages /usr/local/bin/python /opt/***/dags/scripts/batch_data_producer.py 2025-08-13']
[2025-08-14T02:58:26.650+0000] {subprocess.py:86} INFO - Output:
[2025-08-14T02:58:32.147+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-08-14T02:58:32.413+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/scripts/batch_data_producer.py", line 8, in <module>
[2025-08-14T02:58:32.431+0000] {subprocess.py:93} INFO -     import yfinance as yf
[2025-08-14T02:58:32.441+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/yfinance/__init__.py", line 26, in <module>
[2025-08-14T02:58:32.455+0000] {subprocess.py:93} INFO -     from .tickers import Tickers
[2025-08-14T02:58:32.457+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/yfinance/tickers.py", line 26, in <module>
[2025-08-14T02:58:32.472+0000] {subprocess.py:93} INFO -     from . import Ticker, multi
[2025-08-14T02:58:32.474+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/yfinance/multi.py", line 30, in <module>
[2025-08-14T02:58:32.483+0000] {subprocess.py:93} INFO -     import multitasking as _multitasking
[2025-08-14T02:58:32.486+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/multitasking/__init__.py", line 36, in <module>
[2025-08-14T02:58:32.489+0000] {subprocess.py:93} INFO -     class PoolConfig(TypedDict):
[2025-08-14T02:58:32.498+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/multitasking/__init__.py", line 44, in PoolConfig
[2025-08-14T02:58:32.504+0000] {subprocess.py:93} INFO -     engine: Union[type[Thread], type[Process]]  # Execution engine
[2025-08-14T02:58:32.511+0000] {subprocess.py:93} INFO - TypeError: 'type' object is not subscriptable
[2025-08-14T02:58:41.547+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-08-14T02:58:42.076+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-14T02:58:42.134+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_market_batch_pipeline, task_id=fetch_historical_data, execution_date=20250813T000000, start_date=20250814T025825, end_date=20250814T025842
[2025-08-14T02:58:42.383+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 67 for task fetch_historical_data (Bash command failed. The command returned a non-zero exit code 1.; 76747)
[2025-08-14T02:58:42.483+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-14T02:58:42.545+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-14T21:49:48.583+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [queued]>
[2025-08-14T21:49:48.593+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [queued]>
[2025-08-14T21:49:48.594+0000] {taskinstance.py:2170} INFO - Starting attempt 13 of 14
[2025-08-14T21:49:48.606+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): fetch_historical_data> on 2025-08-13 00:00:00+00:00
[2025-08-14T21:49:48.619+0000] {standard_task_runner.py:60} INFO - Started process 31835 to run task
[2025-08-14T21:49:48.628+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'stock_market_batch_pipeline', 'fetch_historical_data', 'scheduled__2025-08-13T00:00:00+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/stock_market_batch_dag.py', '--cfg-path', '/tmp/tmpbfodg40c']
[2025-08-14T21:49:48.630+0000] {standard_task_runner.py:88} INFO - Job 44: Subtask fetch_historical_data
[2025-08-14T21:49:48.765+0000] {task_command.py:423} INFO - Running <TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [running]> on host 0181ae2045ff
[2025-08-14T21:49:48.860+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Basanth Kumar' AIRFLOW_CTX_DAG_ID='stock_market_batch_pipeline' AIRFLOW_CTX_TASK_ID='fetch_historical_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='13' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-13T00:00:00+00:00'
[2025-08-14T21:49:48.866+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-14T21:49:48.867+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n    unset PYTHONNOUSERSITE\n    export PYTHONPATH=/home/***/.local/lib/python3.8/site-packages\n    cd /opt/***/dags/scripts\n    python batch_data_producer.py 2025-08-13\n    ']
[2025-08-14T21:49:48.901+0000] {subprocess.py:86} INFO - Output:
[2025-08-14T21:49:50.107+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-08-14T21:49:50.219+0000] {subprocess.py:93} INFO -   File "batch_data_producer.py", line 8, in <module>
[2025-08-14T21:49:50.223+0000] {subprocess.py:93} INFO -     import yfinance as yf
[2025-08-14T21:49:50.225+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'yfinance'
[2025-08-14T21:49:50.340+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-08-14T21:49:50.484+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-14T21:49:50.502+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_market_batch_pipeline, task_id=fetch_historical_data, execution_date=20250813T000000, start_date=20250814T214948, end_date=20250814T214950
[2025-08-14T21:49:50.671+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 44 for task fetch_historical_data (Bash command failed. The command returned a non-zero exit code 1.; 31835)
[2025-08-14T21:49:50.740+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-14T21:49:50.912+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
