[2025-08-14T02:55:25.685+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [queued]>
[2025-08-14T02:55:25.708+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [queued]>
[2025-08-14T02:55:25.708+0000] {taskinstance.py:2170} INFO - Starting attempt 12 of 13
[2025-08-14T02:55:25.744+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): fetch_historical_data> on 2025-08-13 00:00:00+00:00
[2025-08-14T02:55:25.763+0000] {standard_task_runner.py:60} INFO - Started process 76495 to run task
[2025-08-14T02:55:25.784+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'stock_market_batch_pipeline', 'fetch_historical_data', 'scheduled__2025-08-13T00:00:00+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/stock_market_batch_dag.py', '--cfg-path', '/tmp/tmp8mp6z57t']
[2025-08-14T02:55:25.810+0000] {standard_task_runner.py:88} INFO - Job 60: Subtask fetch_historical_data
[2025-08-14T02:55:25.970+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-08-14T02:55:26.421+0000] {task_command.py:423} INFO - Running <TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [running]> on host 6ea13209f7fc
[2025-08-14T02:55:27.087+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Basanth Kumar' AIRFLOW_CTX_DAG_ID='stock_market_batch_pipeline' AIRFLOW_CTX_TASK_ID='fetch_historical_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='12' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-13T00:00:00+00:00'
[2025-08-14T02:55:27.106+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-14T02:55:27.115+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/usr/local/bin/python /opt/***/dags/scripts/batch_data_producer.py 2025-08-13']
[2025-08-14T02:55:27.263+0000] {subprocess.py:86} INFO - Output:
[2025-08-14T02:55:42.303+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-08-14T02:55:42.380+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/scripts/batch_data_producer.py", line 8, in <module>
[2025-08-14T02:55:42.383+0000] {subprocess.py:93} INFO -     import yfinance as yf
[2025-08-14T02:55:42.388+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/yfinance/__init__.py", line 26, in <module>
[2025-08-14T02:55:42.392+0000] {subprocess.py:93} INFO -     from .tickers import Tickers
[2025-08-14T02:55:42.393+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/yfinance/tickers.py", line 26, in <module>
[2025-08-14T02:55:42.394+0000] {subprocess.py:93} INFO -     from . import Ticker, multi
[2025-08-14T02:55:42.395+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/yfinance/multi.py", line 30, in <module>
[2025-08-14T02:55:42.396+0000] {subprocess.py:93} INFO -     import multitasking as _multitasking
[2025-08-14T02:55:42.397+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/multitasking/__init__.py", line 36, in <module>
[2025-08-14T02:55:42.399+0000] {subprocess.py:93} INFO -     class PoolConfig(TypedDict):
[2025-08-14T02:55:42.400+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/multitasking/__init__.py", line 44, in PoolConfig
[2025-08-14T02:55:42.402+0000] {subprocess.py:93} INFO -     engine: Union[type[Thread], type[Process]]  # Execution engine
[2025-08-14T02:55:42.406+0000] {subprocess.py:93} INFO - TypeError: 'type' object is not subscriptable
[2025-08-14T02:55:43.108+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-08-14T02:55:43.266+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-14T02:55:43.301+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_market_batch_pipeline, task_id=fetch_historical_data, execution_date=20250813T000000, start_date=20250814T025525, end_date=20250814T025543
[2025-08-14T02:55:43.512+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 60 for task fetch_historical_data (Bash command failed. The command returned a non-zero exit code 1.; 76495)
[2025-08-14T02:55:43.544+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-14T02:55:43.691+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-14T21:47:15.838+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [queued]>
[2025-08-14T21:47:15.844+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [queued]>
[2025-08-14T21:47:15.845+0000] {taskinstance.py:2170} INFO - Starting attempt 12 of 12
[2025-08-14T21:47:15.873+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): fetch_historical_data> on 2025-08-13 00:00:00+00:00
[2025-08-14T21:47:15.881+0000] {standard_task_runner.py:60} INFO - Started process 31645 to run task
[2025-08-14T21:47:15.884+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'stock_market_batch_pipeline', 'fetch_historical_data', 'scheduled__2025-08-13T00:00:00+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/stock_market_batch_dag.py', '--cfg-path', '/tmp/tmpzjkn01wj']
[2025-08-14T21:47:15.891+0000] {standard_task_runner.py:88} INFO - Job 41: Subtask fetch_historical_data
[2025-08-14T21:47:15.968+0000] {task_command.py:423} INFO - Running <TaskInstance: stock_market_batch_pipeline.fetch_historical_data scheduled__2025-08-13T00:00:00+00:00 [running]> on host 0181ae2045ff
[2025-08-14T21:47:16.036+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Basanth Kumar' AIRFLOW_CTX_DAG_ID='stock_market_batch_pipeline' AIRFLOW_CTX_TASK_ID='fetch_historical_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='12' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-13T00:00:00+00:00'
[2025-08-14T21:47:16.037+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-14T21:47:16.038+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n    unset PYTHONNOUSERSITE\n    python /opt/***/dags/scripts/batch_data_producer.py 2025-08-13\n    ']
[2025-08-14T21:47:16.045+0000] {subprocess.py:86} INFO - Output:
[2025-08-14T21:47:16.843+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-08-14T21:47:16.855+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/scripts/batch_data_producer.py", line 8, in <module>
[2025-08-14T21:47:16.857+0000] {subprocess.py:93} INFO -     import yfinance as yf
[2025-08-14T21:47:16.857+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'yfinance'
[2025-08-14T21:47:16.937+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-08-14T21:47:16.994+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-14T21:47:17.011+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=stock_market_batch_pipeline, task_id=fetch_historical_data, execution_date=20250813T000000, start_date=20250814T214715, end_date=20250814T214717
[2025-08-14T21:47:17.053+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 41 for task fetch_historical_data (Bash command failed. The command returned a non-zero exit code 1.; 31645)
[2025-08-14T21:47:17.093+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-14T21:47:17.190+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
