[2025-08-14T02:55:25.687+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_market_batch_pipeline.fetch_historical_data manual__2025-08-14T02:36:44+00:00 [queued]>
[2025-08-14T02:55:25.705+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_market_batch_pipeline.fetch_historical_data manual__2025-08-14T02:36:44+00:00 [queued]>
[2025-08-14T02:55:25.707+0000] {taskinstance.py:2170} INFO - Starting attempt 5 of 6
[2025-08-14T02:55:25.746+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): fetch_historical_data> on 2025-08-14 02:36:44+00:00
[2025-08-14T02:55:25.774+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'stock_market_batch_pipeline', 'fetch_historical_data', 'manual__2025-08-14T02:36:44+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/stock_market_batch_dag.py', '--cfg-path', '/tmp/tmpyje82528']
[2025-08-14T02:55:25.763+0000] {standard_task_runner.py:60} INFO - Started process 76494 to run task
[2025-08-14T02:55:25.778+0000] {standard_task_runner.py:88} INFO - Job 59: Subtask fetch_historical_data
[2025-08-14T02:55:25.941+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-08-14T02:55:26.446+0000] {task_command.py:423} INFO - Running <TaskInstance: stock_market_batch_pipeline.fetch_historical_data manual__2025-08-14T02:36:44+00:00 [running]> on host 6ea13209f7fc
[2025-08-14T02:55:26.996+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Basanth Kumar' AIRFLOW_CTX_DAG_ID='stock_market_batch_pipeline' AIRFLOW_CTX_TASK_ID='fetch_historical_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-14T02:36:44+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-14T02:36:44+00:00'
[2025-08-14T02:55:27.025+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-14T02:55:27.037+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/usr/local/bin/python /opt/***/dags/scripts/batch_data_producer.py 2025-08-14']
[2025-08-14T02:55:27.058+0000] {subprocess.py:86} INFO - Output:
[2025-08-14T02:55:42.264+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-08-14T02:55:42.317+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/scripts/batch_data_producer.py", line 8, in <module>
[2025-08-14T02:55:42.325+0000] {subprocess.py:93} INFO -     import yfinance as yf
[2025-08-14T02:55:42.328+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/yfinance/__init__.py", line 26, in <module>
[2025-08-14T02:55:42.347+0000] {subprocess.py:93} INFO -     from .tickers import Tickers
[2025-08-14T02:55:42.363+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/yfinance/tickers.py", line 26, in <module>
[2025-08-14T02:55:42.382+0000] {subprocess.py:93} INFO -     from . import Ticker, multi
[2025-08-14T02:55:42.389+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/yfinance/multi.py", line 30, in <module>
[2025-08-14T02:55:42.397+0000] {subprocess.py:93} INFO -     import multitasking as _multitasking
[2025-08-14T02:55:42.402+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/multitasking/__init__.py", line 36, in <module>
[2025-08-14T02:55:42.404+0000] {subprocess.py:93} INFO -     class PoolConfig(TypedDict):
[2025-08-14T02:55:42.407+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/multitasking/__init__.py", line 44, in PoolConfig
[2025-08-14T02:55:42.410+0000] {subprocess.py:93} INFO -     engine: Union[type[Thread], type[Process]]  # Execution engine
[2025-08-14T02:55:42.413+0000] {subprocess.py:93} INFO - TypeError: 'type' object is not subscriptable
[2025-08-14T02:55:43.109+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-08-14T02:55:43.266+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-14T02:55:43.297+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_market_batch_pipeline, task_id=fetch_historical_data, execution_date=20250814T023644, start_date=20250814T025525, end_date=20250814T025543
[2025-08-14T02:55:43.498+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 59 for task fetch_historical_data (Bash command failed. The command returned a non-zero exit code 1.; 76494)
[2025-08-14T02:55:43.566+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-14T02:55:43.732+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
