[2025-08-14T02:31:08.684+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_market_batch_pipeline.fetch_historical_data manual__2025-08-14T02:20:35+00:00 [queued]>
[2025-08-14T02:31:08.693+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_market_batch_pipeline.fetch_historical_data manual__2025-08-14T02:20:35+00:00 [queued]>
[2025-08-14T02:31:08.693+0000] {taskinstance.py:2170} INFO - Starting attempt 5 of 6
[2025-08-14T02:31:08.702+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): fetch_historical_data> on 2025-08-14 02:20:35+00:00
[2025-08-14T02:31:08.714+0000] {standard_task_runner.py:60} INFO - Started process 74914 to run task
[2025-08-14T02:31:08.725+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'stock_market_batch_pipeline', 'fetch_historical_data', 'manual__2025-08-14T02:20:35+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/stock_market_batch_dag.py', '--cfg-path', '/tmp/tmp55lepv8n']
[2025-08-14T02:31:08.732+0000] {standard_task_runner.py:88} INFO - Job 37: Subtask fetch_historical_data
[2025-08-14T02:31:08.761+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-08-14T02:31:08.802+0000] {task_command.py:423} INFO - Running <TaskInstance: stock_market_batch_pipeline.fetch_historical_data manual__2025-08-14T02:20:35+00:00 [running]> on host 6ea13209f7fc
[2025-08-14T02:31:08.874+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Basanth Kumar' AIRFLOW_CTX_DAG_ID='stock_market_batch_pipeline' AIRFLOW_CTX_TASK_ID='fetch_historical_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-14T02:20:35+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-14T02:20:35+00:00'
[2025-08-14T02:31:08.880+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-14T02:31:08.881+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/scripts/batch_data_producer.py 2025-08-14']
[2025-08-14T02:31:08.888+0000] {subprocess.py:86} INFO - Output:
[2025-08-14T02:31:11.662+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-08-14T02:31:11.677+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/scripts/batch_data_producer.py", line 8, in <module>
[2025-08-14T02:31:11.679+0000] {subprocess.py:93} INFO -     import yfinance as yf
[2025-08-14T02:31:11.680+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/yfinance/__init__.py", line 26, in <module>
[2025-08-14T02:31:11.681+0000] {subprocess.py:93} INFO -     from .tickers import Tickers
[2025-08-14T02:31:11.681+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/yfinance/tickers.py", line 26, in <module>
[2025-08-14T02:31:11.681+0000] {subprocess.py:93} INFO -     from . import Ticker, multi
[2025-08-14T02:31:11.682+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/yfinance/multi.py", line 30, in <module>
[2025-08-14T02:31:11.682+0000] {subprocess.py:93} INFO -     import multitasking as _multitasking
[2025-08-14T02:31:11.683+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/multitasking/__init__.py", line 36, in <module>
[2025-08-14T02:31:11.683+0000] {subprocess.py:93} INFO -     class PoolConfig(TypedDict):
[2025-08-14T02:31:11.683+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/multitasking/__init__.py", line 44, in PoolConfig
[2025-08-14T02:31:11.684+0000] {subprocess.py:93} INFO -     engine: Union[type[Thread], type[Process]]  # Execution engine
[2025-08-14T02:31:11.684+0000] {subprocess.py:93} INFO - TypeError: 'type' object is not subscriptable
[2025-08-14T02:31:12.000+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-08-14T02:31:12.084+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-14T02:31:12.092+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_market_batch_pipeline, task_id=fetch_historical_data, execution_date=20250814T022035, start_date=20250814T023108, end_date=20250814T023112
[2025-08-14T02:31:12.135+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 37 for task fetch_historical_data (Bash command failed. The command returned a non-zero exit code 1.; 74914)
[2025-08-14T02:31:12.181+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-14T02:31:12.241+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
