[2025-08-12T23:14:21.520+0000] {processor.py:161} INFO - Started process (PID=228) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:14:21.522+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:14:21.524+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:14:21.523+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:14:21.586+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:14:21.570+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:14:21.587+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:14:21.636+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.125 seconds
[2025-08-12T23:14:31.805+0000] {processor.py:161} INFO - Started process (PID=238) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:14:31.810+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:14:31.817+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:14:31.815+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:14:31.833+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:14:31.830+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:14:31.834+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:14:31.872+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.075 seconds
[2025-08-12T23:14:42.093+0000] {processor.py:161} INFO - Started process (PID=248) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:14:42.094+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:14:42.095+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:14:42.095+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:14:42.111+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:14:42.109+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:14:42.112+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:14:42.143+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.057 seconds
[2025-08-12T23:14:52.356+0000] {processor.py:161} INFO - Started process (PID=258) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:14:52.359+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:14:52.361+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:14:52.360+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:14:52.383+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:14:52.379+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:14:52.385+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:14:52.430+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.083 seconds
[2025-08-12T23:15:02.717+0000] {processor.py:161} INFO - Started process (PID=268) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:15:02.721+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:15:02.724+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:15:02.723+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:15:02.770+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:15:02.759+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:15:02.773+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:15:02.837+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.156 seconds
[2025-08-12T23:15:13.054+0000] {processor.py:161} INFO - Started process (PID=278) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:15:13.058+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:15:13.060+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:15:13.059+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:15:13.084+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:15:13.078+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:15:13.085+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:15:13.120+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.074 seconds
[2025-08-12T23:15:23.314+0000] {processor.py:161} INFO - Started process (PID=288) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:15:23.319+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:15:23.323+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:15:23.322+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:15:23.357+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:15:23.350+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:15:23.359+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:15:23.404+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.102 seconds
[2025-08-12T23:15:33.585+0000] {processor.py:161} INFO - Started process (PID=298) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:15:33.596+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:15:33.598+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:15:33.597+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:15:33.626+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:15:33.612+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:15:33.626+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:15:33.664+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.092 seconds
[2025-08-12T23:15:43.880+0000] {processor.py:161} INFO - Started process (PID=308) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:15:43.883+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:15:43.885+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:15:43.884+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:15:43.909+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:15:43.902+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:15:43.910+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:15:43.947+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.081 seconds
[2025-08-12T23:15:54.177+0000] {processor.py:161} INFO - Started process (PID=318) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:15:54.181+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:15:54.183+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:15:54.183+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:15:54.200+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:15:54.197+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:15:54.200+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:15:54.241+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.073 seconds
[2025-08-12T23:16:04.419+0000] {processor.py:161} INFO - Started process (PID=328) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:16:04.421+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:16:04.423+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:16:04.422+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:16:04.447+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:16:04.441+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:16:04.449+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:16:04.476+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.069 seconds
[2025-08-12T23:16:14.662+0000] {processor.py:161} INFO - Started process (PID=338) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:16:14.667+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:16:14.669+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:16:14.669+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:16:14.692+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:16:14.687+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:16:14.693+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:16:14.725+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.074 seconds
[2025-08-12T23:16:24.949+0000] {processor.py:161} INFO - Started process (PID=348) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:16:24.954+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:16:24.955+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:16:24.954+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:16:24.975+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:16:24.971+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:16:24.976+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:16:25.004+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.066 seconds
[2025-08-12T23:16:35.198+0000] {processor.py:161} INFO - Started process (PID=358) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:16:35.204+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:16:35.209+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:16:35.207+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:16:35.238+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:16:35.231+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:16:35.239+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:16:35.277+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.088 seconds
[2025-08-12T23:16:45.446+0000] {processor.py:161} INFO - Started process (PID=368) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:16:45.451+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:16:45.453+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:16:45.452+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:16:45.478+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:16:45.475+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:16:45.479+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:16:45.519+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.080 seconds
[2025-08-12T23:16:55.737+0000] {processor.py:161} INFO - Started process (PID=378) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:16:55.740+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:16:55.741+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:16:55.741+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:16:55.763+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:16:55.758+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:16:55.765+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:16:55.816+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.096 seconds
[2025-08-12T23:17:06.057+0000] {processor.py:161} INFO - Started process (PID=388) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:17:06.061+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:17:06.062+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:17:06.062+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:17:06.079+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:17:06.077+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:17:06.079+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:17:06.122+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.072 seconds
[2025-08-12T23:17:16.329+0000] {processor.py:161} INFO - Started process (PID=398) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:17:16.334+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:17:16.336+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:17:16.335+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:17:16.375+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:17:16.361+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:17:16.377+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:17:16.406+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.090 seconds
[2025-08-12T23:17:26.623+0000] {processor.py:161} INFO - Started process (PID=408) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:17:26.627+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:17:26.629+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:17:26.628+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:17:26.662+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:17:26.653+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:17:26.663+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:17:26.720+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.109 seconds
[2025-08-12T23:17:36.924+0000] {processor.py:161} INFO - Started process (PID=418) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:17:36.931+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:17:36.935+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:17:36.934+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:17:36.980+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:17:36.965+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:17:36.984+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:17:37.059+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.151 seconds
[2025-08-12T23:17:47.287+0000] {processor.py:161} INFO - Started process (PID=428) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:17:47.290+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:17:47.294+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:17:47.293+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:17:47.312+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:17:47.310+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:17:47.312+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:17:47.395+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.117 seconds
[2025-08-12T23:17:57.560+0000] {processor.py:161} INFO - Started process (PID=438) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:17:57.562+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:17:57.564+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:17:57.563+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:17:57.585+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:17:57.582+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:17:57.586+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:17:57.627+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.077 seconds
[2025-08-12T23:18:07.759+0000] {processor.py:161} INFO - Started process (PID=448) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:18:07.760+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:18:07.761+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:18:07.761+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:18:07.781+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:18:07.777+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:18:07.781+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:18:07.806+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.057 seconds
[2025-08-12T23:18:17.954+0000] {processor.py:161} INFO - Started process (PID=458) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:18:17.955+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:18:17.956+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:18:17.956+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:18:17.981+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:18:17.972+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:18:17.982+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:18:18.036+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.087 seconds
[2025-08-12T23:18:28.178+0000] {processor.py:161} INFO - Started process (PID=468) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:18:28.181+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:18:28.185+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:18:28.183+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:18:28.223+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:18:28.216+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:18:28.224+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:18:28.253+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.084 seconds
[2025-08-12T23:18:38.434+0000] {processor.py:161} INFO - Started process (PID=478) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:18:38.437+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:18:38.438+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:18:38.438+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:18:38.461+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:18:38.457+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:18:38.462+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:18:38.502+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.089 seconds
[2025-08-12T23:18:48.707+0000] {processor.py:161} INFO - Started process (PID=488) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:18:48.710+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:18:48.712+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:18:48.711+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:18:48.735+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:18:48.730+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:18:48.737+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:18:48.793+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.106 seconds
[2025-08-12T23:18:58.983+0000] {processor.py:161} INFO - Started process (PID=498) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:18:58.986+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:18:58.987+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:18:58.986+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:18:59.007+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:18:59.001+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:18:59.009+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:18:59.043+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.070 seconds
[2025-08-12T23:20:15.577+0000] {processor.py:161} INFO - Started process (PID=227) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:20:15.584+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:20:15.589+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:20:15.589+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:20:15.630+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:20:15.612+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:20:15.634+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:20:15.685+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.129 seconds
[2025-08-12T23:20:25.968+0000] {processor.py:161} INFO - Started process (PID=238) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:20:25.972+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:20:25.975+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:20:25.975+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:20:25.992+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:20:25.990+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:20:25.993+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:20:26.030+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.072 seconds
[2025-08-12T23:20:36.238+0000] {processor.py:161} INFO - Started process (PID=248) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:20:36.240+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:20:36.242+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:20:36.241+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:20:36.276+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:20:36.273+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:20:36.280+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:20:36.328+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.106 seconds
[2025-08-12T23:20:46.562+0000] {processor.py:161} INFO - Started process (PID=258) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:20:46.564+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:20:46.569+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:20:46.568+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:20:46.621+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:20:46.611+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:20:46.623+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:20:46.695+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.151 seconds
[2025-08-12T23:20:57.317+0000] {processor.py:161} INFO - Started process (PID=268) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:20:57.325+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:20:57.329+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:20:57.327+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:20:57.418+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:20:57.409+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:20:57.421+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:20:57.548+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.240 seconds
[2025-08-12T23:21:07.774+0000] {processor.py:161} INFO - Started process (PID=278) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:21:07.776+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:21:07.778+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:21:07.777+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:21:07.798+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:21:07.794+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:21:07.799+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:21:07.868+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.105 seconds
[2025-08-12T23:21:18.234+0000] {processor.py:161} INFO - Started process (PID=288) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:21:18.236+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:21:18.238+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:21:18.237+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:21:18.261+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:21:18.259+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:21:18.263+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:21:18.295+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.073 seconds
[2025-08-12T23:21:28.594+0000] {processor.py:161} INFO - Started process (PID=298) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:21:28.600+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:21:28.608+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:21:28.607+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:21:28.633+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:21:28.627+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:21:28.633+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:21:28.663+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.083 seconds
[2025-08-12T23:21:38.888+0000] {processor.py:161} INFO - Started process (PID=308) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:21:38.891+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:21:38.895+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:21:38.892+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:21:38.943+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:21:38.936+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:21:38.945+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:21:39.000+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.140 seconds
[2025-08-12T23:21:49.242+0000] {processor.py:161} INFO - Started process (PID=318) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:21:49.244+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:21:49.246+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:21:49.245+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:21:49.277+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:21:49.268+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:21:49.278+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:21:49.342+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.126 seconds
[2025-08-12T23:21:59.546+0000] {processor.py:161} INFO - Started process (PID=328) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:21:59.547+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:21:59.549+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:21:59.548+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:21:59.574+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:21:59.572+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:21:59.574+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:21:59.609+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.082 seconds
[2025-08-12T23:22:09.808+0000] {processor.py:161} INFO - Started process (PID=338) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:22:09.816+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:22:09.818+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:22:09.817+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:22:09.852+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:22:09.844+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:22:09.854+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:22:09.902+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.113 seconds
[2025-08-12T23:22:20.135+0000] {processor.py:161} INFO - Started process (PID=348) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:22:20.141+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:22:20.143+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:22:20.142+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:22:20.166+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:22:20.164+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:22:20.167+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:22:20.211+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.089 seconds
[2025-08-12T23:22:30.380+0000] {processor.py:161} INFO - Started process (PID=358) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:22:30.383+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:22:30.384+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:22:30.383+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:22:30.409+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:22:30.406+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:22:30.409+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:22:30.443+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.075 seconds
[2025-08-12T23:22:40.638+0000] {processor.py:161} INFO - Started process (PID=368) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:22:40.641+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:22:40.643+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:22:40.642+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:22:40.664+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:22:40.658+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:22:40.666+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:22:40.692+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.065 seconds
[2025-08-12T23:22:50.866+0000] {processor.py:161} INFO - Started process (PID=378) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:22:50.869+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:22:50.871+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:22:50.870+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:22:50.893+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:22:50.886+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:22:50.894+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:22:50.924+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.069 seconds
[2025-08-12T23:23:01.466+0000] {processor.py:161} INFO - Started process (PID=388) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:23:01.469+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:23:01.471+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:23:01.470+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:23:01.495+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:23:01.483+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:23:01.497+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:23:01.582+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.133 seconds
[2025-08-12T23:23:11.795+0000] {processor.py:161} INFO - Started process (PID=398) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:23:11.810+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:23:11.823+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:23:11.820+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:23:11.854+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:23:11.843+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:23:11.855+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:23:11.890+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.109 seconds
[2025-08-12T23:23:22.107+0000] {processor.py:161} INFO - Started process (PID=408) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:23:22.111+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:23:22.112+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:23:22.111+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:23:22.147+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:23:22.137+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:23:22.147+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:23:22.182+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.093 seconds
[2025-08-12T23:23:32.370+0000] {processor.py:161} INFO - Started process (PID=418) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:23:32.373+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:23:32.376+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:23:32.376+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:23:32.398+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:23:32.389+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:23:32.399+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:23:32.432+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.073 seconds
[2025-08-12T23:23:42.937+0000] {processor.py:161} INFO - Started process (PID=428) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:23:42.940+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:23:42.943+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:23:42.942+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:23:42.975+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:23:42.962+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:23:42.977+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:23:43.018+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.092 seconds
[2025-08-12T23:23:53.269+0000] {processor.py:161} INFO - Started process (PID=438) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:23:53.272+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:23:53.273+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:23:53.273+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:23:53.295+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:23:53.290+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:23:53.295+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:23:53.323+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.070 seconds
[2025-08-12T23:24:03.552+0000] {processor.py:161} INFO - Started process (PID=448) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:24:03.556+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:24:03.558+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:24:03.557+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:24:03.583+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:24:03.576+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:24:03.584+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:24:03.614+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.072 seconds
[2025-08-12T23:24:13.849+0000] {processor.py:161} INFO - Started process (PID=458) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:24:13.857+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:24:13.861+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:24:13.859+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:24:13.888+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:24:13.883+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:24:13.888+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:24:13.953+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.117 seconds
[2025-08-12T23:24:24.230+0000] {processor.py:161} INFO - Started process (PID=468) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:24:24.238+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:24:24.242+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:24:24.240+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:24:24.268+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:24:24.263+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:24:24.269+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:24:24.302+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.099 seconds
[2025-08-12T23:24:34.549+0000] {processor.py:161} INFO - Started process (PID=478) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:24:34.557+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:24:34.559+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:24:34.558+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:24:34.581+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:24:34.575+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:24:34.585+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:24:34.627+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.093 seconds
[2025-08-12T23:24:44.856+0000] {processor.py:161} INFO - Started process (PID=488) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:24:44.865+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:24:44.867+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:24:44.866+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:24:44.905+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:24:44.896+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:24:44.905+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:24:44.960+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.116 seconds
[2025-08-12T23:24:55.236+0000] {processor.py:161} INFO - Started process (PID=498) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:24:55.241+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:24:55.247+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:24:55.244+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:24:55.276+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:24:55.267+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:24:55.278+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:24:55.317+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.104 seconds
[2025-08-12T23:25:05.530+0000] {processor.py:161} INFO - Started process (PID=508) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:25:05.533+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:25:05.535+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:25:05.534+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:25:05.566+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:25:05.559+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:25:05.568+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:25:05.614+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.098 seconds
[2025-08-12T23:25:15.891+0000] {processor.py:161} INFO - Started process (PID=518) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:25:15.894+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:25:15.905+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:25:15.902+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:25:15.936+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:25:15.930+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:25:15.937+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:25:15.999+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.126 seconds
[2025-08-12T23:25:26.244+0000] {processor.py:161} INFO - Started process (PID=528) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:25:26.249+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:25:26.253+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:25:26.252+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:25:26.275+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:25:26.273+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:25:26.276+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:25:26.320+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.093 seconds
[2025-08-12T23:25:36.558+0000] {processor.py:161} INFO - Started process (PID=538) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:25:36.561+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:25:36.563+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:25:36.562+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:25:36.590+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:25:36.584+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:25:36.590+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:25:36.626+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.083 seconds
[2025-08-12T23:25:46.880+0000] {processor.py:161} INFO - Started process (PID=548) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:25:46.882+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:25:46.883+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:25:46.883+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:25:46.910+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:25:46.906+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:25:46.911+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:25:46.950+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.092 seconds
[2025-08-12T23:25:57.152+0000] {processor.py:161} INFO - Started process (PID=558) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:25:57.156+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:25:57.163+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:25:57.158+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:25:57.188+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:25:57.184+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:25:57.190+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:25:57.255+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.121 seconds
[2025-08-12T23:26:07.543+0000] {processor.py:161} INFO - Started process (PID=568) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:26:07.548+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:26:07.549+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:26:07.549+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:26:07.565+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:26:07.563+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:26:07.565+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:26:07.602+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.072 seconds
[2025-08-12T23:26:18.284+0000] {processor.py:161} INFO - Started process (PID=578) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:26:18.289+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:26:18.291+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:26:18.290+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:26:18.329+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:26:18.326+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:26:18.329+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:26:18.380+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.141 seconds
[2025-08-12T23:26:28.663+0000] {processor.py:161} INFO - Started process (PID=588) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:26:28.669+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:26:28.674+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:26:28.673+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:26:28.695+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:26:28.689+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:26:28.696+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:26:28.730+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.082 seconds
[2025-08-12T23:26:38.907+0000] {processor.py:161} INFO - Started process (PID=598) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:26:38.910+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:26:38.913+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:26:38.912+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:26:38.936+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:26:38.934+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:26:38.936+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:26:38.963+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.072 seconds
[2025-08-12T23:26:49.201+0000] {processor.py:161} INFO - Started process (PID=608) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:26:49.203+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:26:49.206+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:26:49.204+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:26:49.237+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:26:49.227+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:26:49.237+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:26:49.274+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.086 seconds
[2025-08-12T23:26:59.512+0000] {processor.py:161} INFO - Started process (PID=618) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:26:59.514+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:26:59.515+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:26:59.515+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:26:59.533+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:26:59.531+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:26:59.533+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:26:59.570+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.070 seconds
[2025-08-12T23:27:09.815+0000] {processor.py:161} INFO - Started process (PID=628) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:27:09.818+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:27:09.820+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:27:09.819+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:27:09.845+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:27:09.838+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:27:09.846+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:27:09.883+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.083 seconds
[2025-08-12T23:27:20.161+0000] {processor.py:161} INFO - Started process (PID=638) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:27:20.164+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:27:20.165+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:27:20.164+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:27:20.192+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:27:20.186+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:27:20.192+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:27:20.239+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.088 seconds
[2025-08-12T23:27:30.412+0000] {processor.py:161} INFO - Started process (PID=648) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:27:30.414+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:27:30.415+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:27:30.415+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:27:30.432+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:27:30.427+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:27:30.435+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:27:30.454+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.051 seconds
[2025-08-12T23:27:40.569+0000] {processor.py:161} INFO - Started process (PID=658) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:27:40.572+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:27:40.576+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:27:40.575+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:27:40.592+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:27:40.586+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:27:40.594+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:27:40.628+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.070 seconds
[2025-08-12T23:27:50.763+0000] {processor.py:161} INFO - Started process (PID=668) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:27:50.765+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:27:50.767+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:27:50.766+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:27:50.787+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:27:50.784+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:27:50.787+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:27:50.834+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.079 seconds
[2025-08-12T23:28:00.978+0000] {processor.py:161} INFO - Started process (PID=678) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:28:00.981+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:28:00.986+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:28:00.985+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:28:01.000+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:28:00.998+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:28:01.001+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:28:01.049+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.083 seconds
[2025-08-12T23:28:11.198+0000] {processor.py:161} INFO - Started process (PID=688) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:28:11.200+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:28:11.202+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:28:11.201+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:28:11.223+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:28:11.215+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:28:11.224+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:28:11.251+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.062 seconds
[2025-08-12T23:28:21.432+0000] {processor.py:161} INFO - Started process (PID=698) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:28:21.434+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:28:21.436+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:28:21.435+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:28:21.458+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:28:21.455+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:28:21.458+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:28:21.480+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.059 seconds
[2025-08-12T23:28:31.685+0000] {processor.py:161} INFO - Started process (PID=708) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:28:31.688+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:28:31.693+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:28:31.689+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:28:31.728+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:28:31.717+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:28:31.730+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:28:31.776+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.108 seconds
[2025-08-12T23:28:41.988+0000] {processor.py:161} INFO - Started process (PID=718) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:28:41.991+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:28:41.993+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:28:41.992+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:28:42.017+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:28:42.010+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:28:42.018+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:28:42.063+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.094 seconds
[2025-08-12T23:28:52.353+0000] {processor.py:161} INFO - Started process (PID=728) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:28:52.359+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:28:52.360+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:28:52.360+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:28:52.388+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:28:52.381+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:28:52.389+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:28:52.428+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.090 seconds
[2025-08-12T23:29:02.620+0000] {processor.py:161} INFO - Started process (PID=738) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:29:02.625+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:29:02.627+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:29:02.627+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:29:02.654+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:29:02.648+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:29:02.655+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:29:02.693+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.086 seconds
[2025-08-12T23:29:12.920+0000] {processor.py:161} INFO - Started process (PID=748) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:29:12.923+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:29:12.924+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:29:12.924+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:29:12.949+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:29:12.941+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:29:12.952+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:29:12.995+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.089 seconds
[2025-08-12T23:29:23.235+0000] {processor.py:161} INFO - Started process (PID=758) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:29:23.240+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:29:23.242+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:29:23.241+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:29:23.270+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:29:23.261+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:29:23.271+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:29:23.307+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.094 seconds
[2025-08-12T23:29:33.523+0000] {processor.py:161} INFO - Started process (PID=768) to work on /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:29:33.527+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/stock_market_batch_dag.py for tasks to queue
[2025-08-12T23:29:33.529+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:29:33.528+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:29:33.549+0000] {logging_mixin.py:188} INFO - [2025-08-12T23:29:33.546+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/stock_market_batch_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_market_batch_dag.py", line 34, in <module>
    consume_historical_data = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'fetch_historical_data' has already been added to the DAG
[2025-08-12T23:29:33.550+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_market_batch_dag.py
[2025-08-12T23:29:33.598+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/stock_market_batch_dag.py took 0.098 seconds
