[2025-08-14T02:51:04.718+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_market_batch_pipeline.fetch_historical_data manual__2025-08-14T02:43:26+00:00 [queued]>
[2025-08-14T02:51:04.734+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_market_batch_pipeline.fetch_historical_data manual__2025-08-14T02:43:26+00:00 [queued]>
[2025-08-14T02:51:04.736+0000] {taskinstance.py:2170} INFO - Starting attempt 3 of 4
[2025-08-14T02:51:04.751+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): fetch_historical_data> on 2025-08-14 02:43:26+00:00
[2025-08-14T02:51:04.768+0000] {standard_task_runner.py:60} INFO - Started process 76183 to run task
[2025-08-14T02:51:04.774+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'stock_market_batch_pipeline', 'fetch_historical_data', 'manual__2025-08-14T02:43:26+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/stock_market_batch_dag.py', '--cfg-path', '/tmp/tmpxxg_a9ee']
[2025-08-14T02:51:04.787+0000] {standard_task_runner.py:88} INFO - Job 56: Subtask fetch_historical_data
[2025-08-14T02:51:04.829+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-08-14T02:51:04.944+0000] {task_command.py:423} INFO - Running <TaskInstance: stock_market_batch_pipeline.fetch_historical_data manual__2025-08-14T02:43:26+00:00 [running]> on host 6ea13209f7fc
[2025-08-14T02:51:05.078+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Basanth Kumar' AIRFLOW_CTX_DAG_ID='stock_market_batch_pipeline' AIRFLOW_CTX_TASK_ID='fetch_historical_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-14T02:43:26+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-14T02:43:26+00:00'
[2025-08-14T02:51:05.086+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-14T02:51:05.088+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/scripts/batch_data_producer.py 2025-08-14']
[2025-08-14T02:51:05.117+0000] {subprocess.py:86} INFO - Output:
[2025-08-14T02:51:17.820+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-08-14T02:51:17.841+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/scripts/batch_data_producer.py", line 8, in <module>
[2025-08-14T02:51:17.843+0000] {subprocess.py:93} INFO -     import yfinance as yf
[2025-08-14T02:51:17.846+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/yfinance/__init__.py", line 26, in <module>
[2025-08-14T02:51:17.851+0000] {subprocess.py:93} INFO -     from .tickers import Tickers
[2025-08-14T02:51:17.851+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/yfinance/tickers.py", line 26, in <module>
[2025-08-14T02:51:17.852+0000] {subprocess.py:93} INFO -     from . import Ticker, multi
[2025-08-14T02:51:17.852+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/yfinance/multi.py", line 30, in <module>
[2025-08-14T02:51:17.853+0000] {subprocess.py:93} INFO -     import multitasking as _multitasking
[2025-08-14T02:51:17.853+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/multitasking/__init__.py", line 36, in <module>
[2025-08-14T02:51:17.854+0000] {subprocess.py:93} INFO -     class PoolConfig(TypedDict):
[2025-08-14T02:51:17.855+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/multitasking/__init__.py", line 44, in PoolConfig
[2025-08-14T02:51:17.855+0000] {subprocess.py:93} INFO -     engine: Union[type[Thread], type[Process]]  # Execution engine
[2025-08-14T02:51:17.855+0000] {subprocess.py:93} INFO - TypeError: 'type' object is not subscriptable
[2025-08-14T02:51:19.060+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-08-14T02:51:19.199+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-14T02:51:19.209+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_market_batch_pipeline, task_id=fetch_historical_data, execution_date=20250814T024326, start_date=20250814T025104, end_date=20250814T025119
[2025-08-14T02:51:19.266+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 56 for task fetch_historical_data (Bash command failed. The command returned a non-zero exit code 1.; 76183)
[2025-08-14T02:51:19.351+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-14T02:51:19.502+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
