[2025-08-14T03:03:47.849+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_market_batch_pipeline.fetch_historical_data manual__2025-08-14T02:51:23+00:00 [queued]>
[2025-08-14T03:03:47.895+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_market_batch_pipeline.fetch_historical_data manual__2025-08-14T02:51:23+00:00 [queued]>
[2025-08-14T03:03:47.896+0000] {taskinstance.py:2170} INFO - Starting attempt 4 of 4
[2025-08-14T03:03:47.955+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): fetch_historical_data> on 2025-08-14 02:51:23+00:00
[2025-08-14T03:03:47.970+0000] {standard_task_runner.py:60} INFO - Started process 77255 to run task
[2025-08-14T03:03:47.990+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'stock_market_batch_pipeline', 'fetch_historical_data', 'manual__2025-08-14T02:51:23+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/stock_market_batch_dag.py', '--cfg-path', '/tmp/tmp3ci8onbs']
[2025-08-14T03:03:48.001+0000] {standard_task_runner.py:88} INFO - Job 82: Subtask fetch_historical_data
[2025-08-14T03:03:48.065+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-08-14T03:03:48.169+0000] {task_command.py:423} INFO - Running <TaskInstance: stock_market_batch_pipeline.fetch_historical_data manual__2025-08-14T02:51:23+00:00 [running]> on host 6ea13209f7fc
[2025-08-14T03:03:48.327+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Basanth Kumar' AIRFLOW_CTX_DAG_ID='stock_market_batch_pipeline' AIRFLOW_CTX_TASK_ID='fetch_historical_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-14T02:51:23+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-14T02:51:23+00:00'
[2025-08-14T03:03:48.332+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-14T03:03:48.337+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n    export PYTHONNOUSERSITE=1\n    export PYTHONPATH=/usr/local/lib/python3.8/site-packages\n    /usr/local/bin/python /opt/***/dags/scripts/batch_data_producer.py 2025-08-14\n    ']
[2025-08-14T03:03:48.367+0000] {subprocess.py:86} INFO - Output:
[2025-08-14T03:03:48.464+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-08-14T03:03:48.467+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/scripts/batch_data_producer.py", line 7, in <module>
[2025-08-14T03:03:48.471+0000] {subprocess.py:93} INFO -     import pandas as pd
[2025-08-14T03:03:48.474+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'pandas'
[2025-08-14T03:03:48.477+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-08-14T03:03:48.518+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-14T03:03:48.526+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=stock_market_batch_pipeline, task_id=fetch_historical_data, execution_date=20250814T025123, start_date=20250814T030347, end_date=20250814T030348
[2025-08-14T03:03:48.582+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 82 for task fetch_historical_data (Bash command failed. The command returned a non-zero exit code 1.; 77255)
[2025-08-14T03:03:48.623+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-14T03:03:48.676+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
